### ISSUE TITLE
Full VIA support

### ISSUE THREAD

**Issue by leovander** [coseyfannitutti/mysterium#14]
I haven't seen any updates to the mysterium hex on the VIA website, and I saw your note about the media keys in your comment linked below.

As of now is there any way to enable those media keys in VIA without having to have you compile a specific layout? Or should I just keep an eye out on the VIA website?

Thanks!

https://github.com/coseyfannitutti/mysterium/issues/9#issuecomment-641700514

**Comment by coseyfannitutti** [comment]
Yeah, I'm sure it will update eventually. I'm not sure how often they recompile, but it has been fixed in QMK. Once VIA recompiles firmware on their end, media keys should work for all V-USB boards that have updated the firmware accordingly.

For now the only way is to download the latest version of the QMK repository and compile the firmware via command line. You can unzip the attached file below for the updated .hex, though.

[coseyfannitutti_mysterium_via.hex.zip](https://github.com/coseyfannitutti/mysterium/files/5286717/coseyfannitutti_mysterium_via.hex.zip)
